### ISSUE TITLE
Destination presets

### ISSUE THREAD

**Issue by endgrant** [Dzman17/AirBooks#9]
Compile a brief list of flights that the user may be able to select when searching for a flight.
Just a simple list, I will paste it into the combo box later.

**Comment by DanielES01** [comment]
New York City, Los Angeles, Chicago, Houston, Phoenix, Philadelphia, San Diego, Dallas, Austin, Washington DC, Boston, Las Vegas, Detroit, Baltimore, Kansas City, Atlanta, Miami, Milwaukee, Portland, Seattle, Indianapolis

**Comment by endgrant** [comment]
Added default destinations to the combo box when searching for flights.
